### ISSUE TITLE
Reopen log

### ISSUE THREAD

**Issue by sirkonst** [chmouel/ftp-cloudfs#42]
How reopen log file if used log-file option?

**Comment by reidrac** [comment]
Logging into a log file is usually worse than logging to a performant syslog such as rsyslog. That's our preferred configuration when deploying the service, and because of that we didn't add support for log rotation when logging into a file.

The right way of doing this would be adding support for SIGHUP in the signal handler and then re-open the log file.

I think that the syslog option is better, but let me know if you want we add support for that!

**Comment by sirkonst** [comment]
Thanks for answer. I think, I going to migrate to syslog for logging.

But adding SIGHUP is good idea for features.

**Comment by reidrac** [comment]
OK, I'll add it to the TODO.

Thanks for the report!
